# Generated by Django 5.2.7 on 2025-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactinfo_exhibitedworks_order_pricelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitedworks',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
