# Generated by Django 5.2.7 on 2025-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exhibitedworks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitedworks',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
