# Generated by Django 5.2.7 on 2025-10-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_exhibitedworks_price_alter_pricelist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('year', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ImageItem',
        ),
    ]
