# Generated by Django 5.2.7 on 2025-10-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_drawings_delete_imageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawings',
            name='imgbb_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
