# Generated by Django 5.2.7 on 2025-10-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_drawings_imgbb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawings',
            name='imgbb_url',
        ),
    ]
