# Generated by Django 5.2.7 on 2025-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_drawings_imgbb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawings',
            name='title',
        ),
        migrations.AddField(
            model_name='drawings',
            name='Commissioned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exhibitedworks',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
